baseURL = "https://mecgoonline.github.io/"
languageCode = "en-us"
title = "MEC Online Learning"
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
#and corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = "Abdellah"
  # Description of the site, will be used in meta information
  description = ""
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = true
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"

[[menu.shortcuts]] 
name = "<i class='fas fa-comments'></i> Slack Workspace"
#identifier = "hugodoc"
url = "https://join.slack.com/t/lagccmaelab/shared_invite/zt-n8ztfkt2-WxUo~FAy3mwd4Vkdgv3gxA"
weight = 5


[[menu.shortcuts]] 
name = "<i class='fas fa-building'></i> Civil Engineering Major"
#identifier = "ds"
url = "https://www.laguardia.edu/majors/civil-engineering/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-microchip'></i> Electrical Engineering Major"
#identifier = "ds"
url = "https://www.laguardia.edu/majors/electrical-engineering/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bolt'></i> Energy Technician Major"
#identifier = "ds"
url = "https://www.laguardia.edu/majors/energy-technician-electrical/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fab fa-slack-hash'></i> Mechanical Engineering"
#identifier = "ds"
url = "https://www.laguardia.edu/majors/mechanical-engineering"
weight = 40

[[menu.shortcuts]]
name = "<i class='fa fa-globe'></i> Engineering: Earth System Science"
#identifier = "ds"
url = "https://www.laguardia.edu/majors/earth-system-science/"
weight = 50



[menu]

[[menu.main]]
parent = "engineering"
name = "MAE100"
url = "/engineering/MAE100.md"
